const todos = [
  { id: "1", 
    text: "Сделать проектную работу", 
    isChecked: false },
  { id: "2", 
    text: "Полить цветы", 
    isChecked: false },
  { id: "3", 
    text: "Пройти туториал по Реакту", 
    isChecked: false },
  { id: "4", 
    text: "Сделать фронт для своего проекта", 
    isChecked: false },
  { id: "5", 
    text: "Погулять с собакой", 
    isChecked: false },
  { id: "6", 
    text: "Разобраться в замыканиях", 
    isChecked: false },
  { id: "7", 
    text: "Решить задачу на Codewars", 
    isChecked: false },
];

export { todos };
